FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.22@sha256:b1e05e2c918f52c59d39ce7d5844f73b2f4511f7734add8bb98c9ecdd4443365 as build

ARG TARGETOS
ARG TARGETARCH

ADD . /src
WORKDIR /src

RUN make build

FROM docker.io/library/alpine:3.19@sha256:c5b1261d6d3e43071626931fc004f70149baeba2c8ec672bd4f27761f8e1ad6b

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="git-sv"
LABEL org.opencontainers.image.url="https://github.com/thegeeklab/git-sv"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/git-sv"
LABEL org.opencontainers.image.documentation="https://github.com/thegeeklab/git-sv"

RUN apk --update add --no-cache git && \
    rm -rf /var/cache/apk/* && \
    rm -rf /tmp/*

COPY --from=build /src/dist/git-sv /bin/git-sv
ENTRYPOINT ["/bin/git-sv"]
